name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set up Docker Buildx
        run: |
          docker buildx create --use --name mybuilder
          docker buildx inspect mybuilder --bootstrap

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          builder: mybuilder
          platforms: linux/amd64,linux/arm64  # Specify the platforms you want to support
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
